docs/environment-setup.md added
DukeManh/eidetically pull request #63
Opened 2022-01-14 04:33 UTC by tpmai22

I have added environment setup docs for new dev which included troubleshooting guide to run the project on window

2022-01-14 20:32 UTC, DukeManh requested changes

2022-01-14 20:32 UTC, DukeManh commented on docs/environment-setup.md
> +## Troubleshooting for starting the project on a Window machine:
We should encourage people to install WSL2  so they don't run into problems with Windows CMD in the future

2022-01-15 00:42 UTC, tpmai22 commented on docs/environment-setup.md
> +## Troubleshooting for starting the project on a Window machine:
@DukeManh so I suggest to change to <h2> Encouraging to install WSL2 </h2>

2022-01-15 21:19 UTC, DukeManh requested changes

2022-01-15 21:19 UTC, DukeManh commented on docs/environment-setup.md
> +We use `pnpm` because ton of benefit that it brought to the table ([More on the benefits of pnpm](https://pnpm.io/motivation)).
```suggestion
We use `pnpm` as our package manager. 
Learn more about [pnpm](https://pnpm.io/motivation)
```

2022-01-15 21:19 UTC, DukeManh commented on docs/environment-setup.md
> +- [Install WSL2 on Window](#install-wsl2-on-window)
```suggestion
- [Install WSL2 on Window](#install-wsl2-on-window)
- [Instal project dependencies](#install-project-dependencies)
```

2022-01-15 21:19 UTC, DukeManh commented on docs/environment-setup.md
> +## Install WSL2 on Window
Move this up before installing dependencies because it's the first step

2022-01-15 22:14 UTC, DukeManh requested changes

2022-01-15 22:14 UTC, DukeManh commented on docs/environment-setup.md
> +- - [Install WSL2 on Window](#install-wsl2-on-window)
hmm,

2022-01-15 22:17 UTC, DukeManh requested changes

2022-01-15 22:17 UTC, DukeManh commented on docs/environment-setup.md
> +[After installing the prerequisites and pnpm:](#after-installing-the-prerequisites-and-pnpm)
Start the Frontend development server

2022-01-15 22:19 UTC, DukeManh requested changes

2022-01-15 22:19 UTC, DukeManh commented on docs/environment-setup.md
> +### Table of Contents
Could you make this `h2 - ##`, directly following `h1`.

2022-01-15 22:19 UTC, DukeManh commented on docs/environment-setup.md
> +## Install project dependencies
This should be `###`

2022-01-15 22:19 UTC, DukeManh commented on docs/environment-setup.md
> +## Install WSL2 on Window
`###`

2022-01-15 23:25 UTC, DukeManh approved these changes

2022-01-15 23:25 UTC, DukeManh commented
Looks great, thank James. Can you merge it yourself?

2022-01-15 23:43 UTC, merged